from .search_by_education import search_by_education
from .search_by_income import search_by_income
from .search_by_marks import search_by_marks
from .scholarship_details import get_scholarship_details
